//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.06 at 03:53:18 PM IST 
//


package com.concept.crew.info.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for AssetExchange complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AssetExchange">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="assetExchangeSource" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="30"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="exchangeCode" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="100"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="mic" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="100"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="micStatus" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="listingEffectiveDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="bbgExchangeId" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="50"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="bbgExchangeTicker" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="50"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="cityOfListing" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="100"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="countryOfListing" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="10"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="delistingDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="exchangeName" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="100"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="listingStatus" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="50"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="lotSize" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="minTradeQuantity" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="isPrimaryListing" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="cityOfSubMarket" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="100"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="subMarketExchange" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="100"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="subMarketMic" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="10"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="subMarketMicStatus" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="50"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AssetExchange", propOrder = {
    "assetExchangeSource",
    "exchangeCode",
    "mic",
    "micStatus",
    "listingEffectiveDate",
    "bbgExchangeId",
    "bbgExchangeTicker",
    "cityOfListing",
    "countryOfListing",
    "delistingDate",
    "exchangeName",
    "listingStatus",
    "lotSize",
    "minTradeQuantity",
    "isPrimaryListing",
    "cityOfSubMarket",
    "subMarketExchange",
    "subMarketMic",
    "subMarketMicStatus"
})
public class AssetExchange {

    protected String assetExchangeSource;
    protected String exchangeCode;
    protected String mic;
    protected Boolean micStatus;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar listingEffectiveDate;
    protected String bbgExchangeId;
    protected String bbgExchangeTicker;
    protected String cityOfListing;
    protected String countryOfListing;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar delistingDate;
    protected String exchangeName;
    protected String listingStatus;
    protected Double lotSize;
    protected Double minTradeQuantity;
    protected Boolean isPrimaryListing;
    protected String cityOfSubMarket;
    protected String subMarketExchange;
    protected String subMarketMic;
    protected String subMarketMicStatus;

    /**
     * Gets the value of the assetExchangeSource property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAssetExchangeSource() {
        return assetExchangeSource;
    }

    /**
     * Sets the value of the assetExchangeSource property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAssetExchangeSource(String value) {
        this.assetExchangeSource = value;
    }

    /**
     * Gets the value of the exchangeCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExchangeCode() {
        return exchangeCode;
    }

    /**
     * Sets the value of the exchangeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExchangeCode(String value) {
        this.exchangeCode = value;
    }

    /**
     * Gets the value of the mic property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMic() {
        return mic;
    }

    /**
     * Sets the value of the mic property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMic(String value) {
        this.mic = value;
    }

    /**
     * Gets the value of the micStatus property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isMicStatus() {
        return micStatus;
    }

    /**
     * Sets the value of the micStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setMicStatus(Boolean value) {
        this.micStatus = value;
    }

    /**
     * Gets the value of the listingEffectiveDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getListingEffectiveDate() {
        return listingEffectiveDate;
    }

    /**
     * Sets the value of the listingEffectiveDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setListingEffectiveDate(XMLGregorianCalendar value) {
        this.listingEffectiveDate = value;
    }

    /**
     * Gets the value of the bbgExchangeId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBbgExchangeId() {
        return bbgExchangeId;
    }

    /**
     * Sets the value of the bbgExchangeId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBbgExchangeId(String value) {
        this.bbgExchangeId = value;
    }

    /**
     * Gets the value of the bbgExchangeTicker property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBbgExchangeTicker() {
        return bbgExchangeTicker;
    }

    /**
     * Sets the value of the bbgExchangeTicker property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBbgExchangeTicker(String value) {
        this.bbgExchangeTicker = value;
    }

    /**
     * Gets the value of the cityOfListing property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCityOfListing() {
        return cityOfListing;
    }

    /**
     * Sets the value of the cityOfListing property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCityOfListing(String value) {
        this.cityOfListing = value;
    }

    /**
     * Gets the value of the countryOfListing property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountryOfListing() {
        return countryOfListing;
    }

    /**
     * Sets the value of the countryOfListing property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountryOfListing(String value) {
        this.countryOfListing = value;
    }

    /**
     * Gets the value of the delistingDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDelistingDate() {
        return delistingDate;
    }

    /**
     * Sets the value of the delistingDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDelistingDate(XMLGregorianCalendar value) {
        this.delistingDate = value;
    }

    /**
     * Gets the value of the exchangeName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExchangeName() {
        return exchangeName;
    }

    /**
     * Sets the value of the exchangeName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExchangeName(String value) {
        this.exchangeName = value;
    }

    /**
     * Gets the value of the listingStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getListingStatus() {
        return listingStatus;
    }

    /**
     * Sets the value of the listingStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setListingStatus(String value) {
        this.listingStatus = value;
    }

    /**
     * Gets the value of the lotSize property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getLotSize() {
        return lotSize;
    }

    /**
     * Sets the value of the lotSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setLotSize(Double value) {
        this.lotSize = value;
    }

    /**
     * Gets the value of the minTradeQuantity property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getMinTradeQuantity() {
        return minTradeQuantity;
    }

    /**
     * Sets the value of the minTradeQuantity property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setMinTradeQuantity(Double value) {
        this.minTradeQuantity = value;
    }

    /**
     * Gets the value of the isPrimaryListing property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsPrimaryListing() {
        return isPrimaryListing;
    }

    /**
     * Sets the value of the isPrimaryListing property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsPrimaryListing(Boolean value) {
        this.isPrimaryListing = value;
    }

    /**
     * Gets the value of the cityOfSubMarket property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCityOfSubMarket() {
        return cityOfSubMarket;
    }

    /**
     * Sets the value of the cityOfSubMarket property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCityOfSubMarket(String value) {
        this.cityOfSubMarket = value;
    }

    /**
     * Gets the value of the subMarketExchange property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubMarketExchange() {
        return subMarketExchange;
    }

    /**
     * Sets the value of the subMarketExchange property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubMarketExchange(String value) {
        this.subMarketExchange = value;
    }

    /**
     * Gets the value of the subMarketMic property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubMarketMic() {
        return subMarketMic;
    }

    /**
     * Sets the value of the subMarketMic property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubMarketMic(String value) {
        this.subMarketMic = value;
    }

    /**
     * Gets the value of the subMarketMicStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSubMarketMicStatus() {
        return subMarketMicStatus;
    }

    /**
     * Sets the value of the subMarketMicStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSubMarketMicStatus(String value) {
        this.subMarketMicStatus = value;
    }

}
