//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.15 at 11:31:31 PM IST 
//


package com.concept.crew.info.jaxb;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for CallSchedule complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CallSchedule">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="callScheduleSource" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="30"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="isCallDefeased" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="callStartDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="callEndDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="callValidity" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="callFrequencyCode" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="100"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="callPrice" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="callMaxNoticeDays" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="callMinNoticeDays" type="{http://www.w3.org/2001/XMLSchema}long" minOccurs="0"/>
 *         &lt;element name="optionStyle" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="200"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="optionStyleSubType" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="200"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="callNoticeDaysConvention" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="100"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="callMethodType" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="200"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="callMethodSubType" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="200"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="isCompoundAccretedValue" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="callPriceLinkage" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="50"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="isPriceDifferentFromPar" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="circumstanceCallType" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="100"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="equityClawbackPercent" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="makewholeBenchmark" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="100"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="makewholeSpread" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="softCallConversionPercent" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="softCallConversionPercentPremium" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="softCallDays" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="softCallTriggerValue" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CallSchedule", propOrder = {
    "callScheduleSource",
    "isCallDefeased",
    "callStartDate",
    "callEndDate",
    "callValidity",
    "callFrequencyCode",
    "callPrice",
    "callMaxNoticeDays",
    "callMinNoticeDays",
    "optionStyle",
    "optionStyleSubType",
    "callNoticeDaysConvention",
    "callMethodType",
    "callMethodSubType",
    "isCompoundAccretedValue",
    "callPriceLinkage",
    "isPriceDifferentFromPar",
    "circumstanceCallType",
    "equityClawbackPercent",
    "makewholeBenchmark",
    "makewholeSpread",
    "softCallConversionPercent",
    "softCallConversionPercentPremium",
    "softCallDays",
    "softCallTriggerValue"
})
public class CallSchedule {

    protected String callScheduleSource;
    protected Boolean isCallDefeased;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar callStartDate;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar callEndDate;
    protected Long callValidity;
    protected String callFrequencyCode;
    protected BigDecimal callPrice;
    protected Long callMaxNoticeDays;
    protected Long callMinNoticeDays;
    protected String optionStyle;
    protected String optionStyleSubType;
    protected String callNoticeDaysConvention;
    protected String callMethodType;
    protected String callMethodSubType;
    protected Boolean isCompoundAccretedValue;
    protected String callPriceLinkage;
    protected Boolean isPriceDifferentFromPar;
    protected String circumstanceCallType;
    protected Double equityClawbackPercent;
    protected String makewholeBenchmark;
    protected Double makewholeSpread;
    protected Double softCallConversionPercent;
    protected Double softCallConversionPercentPremium;
    protected Double softCallDays;
    protected Double softCallTriggerValue;

    /**
     * Gets the value of the callScheduleSource property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCallScheduleSource() {
        return callScheduleSource;
    }

    /**
     * Sets the value of the callScheduleSource property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCallScheduleSource(String value) {
        this.callScheduleSource = value;
    }

    /**
     * Gets the value of the isCallDefeased property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsCallDefeased() {
        return isCallDefeased;
    }

    /**
     * Sets the value of the isCallDefeased property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsCallDefeased(Boolean value) {
        this.isCallDefeased = value;
    }

    /**
     * Gets the value of the callStartDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCallStartDate() {
        return callStartDate;
    }

    /**
     * Sets the value of the callStartDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCallStartDate(XMLGregorianCalendar value) {
        this.callStartDate = value;
    }

    /**
     * Gets the value of the callEndDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCallEndDate() {
        return callEndDate;
    }

    /**
     * Sets the value of the callEndDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCallEndDate(XMLGregorianCalendar value) {
        this.callEndDate = value;
    }

    /**
     * Gets the value of the callValidity property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getCallValidity() {
        return callValidity;
    }

    /**
     * Sets the value of the callValidity property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setCallValidity(Long value) {
        this.callValidity = value;
    }

    /**
     * Gets the value of the callFrequencyCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCallFrequencyCode() {
        return callFrequencyCode;
    }

    /**
     * Sets the value of the callFrequencyCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCallFrequencyCode(String value) {
        this.callFrequencyCode = value;
    }

    /**
     * Gets the value of the callPrice property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getCallPrice() {
        return callPrice;
    }

    /**
     * Sets the value of the callPrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setCallPrice(BigDecimal value) {
        this.callPrice = value;
    }

    /**
     * Gets the value of the callMaxNoticeDays property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getCallMaxNoticeDays() {
        return callMaxNoticeDays;
    }

    /**
     * Sets the value of the callMaxNoticeDays property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setCallMaxNoticeDays(Long value) {
        this.callMaxNoticeDays = value;
    }

    /**
     * Gets the value of the callMinNoticeDays property.
     * 
     * @return
     *     possible object is
     *     {@link Long }
     *     
     */
    public Long getCallMinNoticeDays() {
        return callMinNoticeDays;
    }

    /**
     * Sets the value of the callMinNoticeDays property.
     * 
     * @param value
     *     allowed object is
     *     {@link Long }
     *     
     */
    public void setCallMinNoticeDays(Long value) {
        this.callMinNoticeDays = value;
    }

    /**
     * Gets the value of the optionStyle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOptionStyle() {
        return optionStyle;
    }

    /**
     * Sets the value of the optionStyle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOptionStyle(String value) {
        this.optionStyle = value;
    }

    /**
     * Gets the value of the optionStyleSubType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOptionStyleSubType() {
        return optionStyleSubType;
    }

    /**
     * Sets the value of the optionStyleSubType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOptionStyleSubType(String value) {
        this.optionStyleSubType = value;
    }

    /**
     * Gets the value of the callNoticeDaysConvention property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCallNoticeDaysConvention() {
        return callNoticeDaysConvention;
    }

    /**
     * Sets the value of the callNoticeDaysConvention property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCallNoticeDaysConvention(String value) {
        this.callNoticeDaysConvention = value;
    }

    /**
     * Gets the value of the callMethodType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCallMethodType() {
        return callMethodType;
    }

    /**
     * Sets the value of the callMethodType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCallMethodType(String value) {
        this.callMethodType = value;
    }

    /**
     * Gets the value of the callMethodSubType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCallMethodSubType() {
        return callMethodSubType;
    }

    /**
     * Sets the value of the callMethodSubType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCallMethodSubType(String value) {
        this.callMethodSubType = value;
    }

    /**
     * Gets the value of the isCompoundAccretedValue property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsCompoundAccretedValue() {
        return isCompoundAccretedValue;
    }

    /**
     * Sets the value of the isCompoundAccretedValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsCompoundAccretedValue(Boolean value) {
        this.isCompoundAccretedValue = value;
    }

    /**
     * Gets the value of the callPriceLinkage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCallPriceLinkage() {
        return callPriceLinkage;
    }

    /**
     * Sets the value of the callPriceLinkage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCallPriceLinkage(String value) {
        this.callPriceLinkage = value;
    }

    /**
     * Gets the value of the isPriceDifferentFromPar property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsPriceDifferentFromPar() {
        return isPriceDifferentFromPar;
    }

    /**
     * Sets the value of the isPriceDifferentFromPar property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsPriceDifferentFromPar(Boolean value) {
        this.isPriceDifferentFromPar = value;
    }

    /**
     * Gets the value of the circumstanceCallType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCircumstanceCallType() {
        return circumstanceCallType;
    }

    /**
     * Sets the value of the circumstanceCallType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCircumstanceCallType(String value) {
        this.circumstanceCallType = value;
    }

    /**
     * Gets the value of the equityClawbackPercent property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getEquityClawbackPercent() {
        return equityClawbackPercent;
    }

    /**
     * Sets the value of the equityClawbackPercent property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setEquityClawbackPercent(Double value) {
        this.equityClawbackPercent = value;
    }

    /**
     * Gets the value of the makewholeBenchmark property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMakewholeBenchmark() {
        return makewholeBenchmark;
    }

    /**
     * Sets the value of the makewholeBenchmark property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMakewholeBenchmark(String value) {
        this.makewholeBenchmark = value;
    }

    /**
     * Gets the value of the makewholeSpread property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getMakewholeSpread() {
        return makewholeSpread;
    }

    /**
     * Sets the value of the makewholeSpread property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setMakewholeSpread(Double value) {
        this.makewholeSpread = value;
    }

    /**
     * Gets the value of the softCallConversionPercent property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getSoftCallConversionPercent() {
        return softCallConversionPercent;
    }

    /**
     * Sets the value of the softCallConversionPercent property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setSoftCallConversionPercent(Double value) {
        this.softCallConversionPercent = value;
    }

    /**
     * Gets the value of the softCallConversionPercentPremium property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getSoftCallConversionPercentPremium() {
        return softCallConversionPercentPremium;
    }

    /**
     * Sets the value of the softCallConversionPercentPremium property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setSoftCallConversionPercentPremium(Double value) {
        this.softCallConversionPercentPremium = value;
    }

    /**
     * Gets the value of the softCallDays property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getSoftCallDays() {
        return softCallDays;
    }

    /**
     * Sets the value of the softCallDays property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setSoftCallDays(Double value) {
        this.softCallDays = value;
    }

    /**
     * Gets the value of the softCallTriggerValue property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getSoftCallTriggerValue() {
        return softCallTriggerValue;
    }

    /**
     * Sets the value of the softCallTriggerValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setSoftCallTriggerValue(Double value) {
        this.softCallTriggerValue = value;
    }

}
