//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.15 at 11:31:31 PM IST 
//


package com.concept.crew.info.jaxb;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for Instrument complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Instrument">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="instrumentId" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="datasetId" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="version" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="newIssue" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="20"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="instrumentGrade">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="25"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="lastModifiedDate" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="source">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="30"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="hasAdditionalCredit" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="alternativePrincipalCcyCode" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="3"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="amtIssuedPublic" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="auctionType" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="100"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="averageLifeDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="isBankQualified" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="isBondLinked" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="benchmarkISIN" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="12"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="instrumentInsuranceType" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="100"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="tranche" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="100"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="instrumentSwapType" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="100"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="businessDayConvention" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="100"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="calculationType" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="100"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="capitalPurpose" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="100"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="classification" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="100"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="classificationSubType" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="100"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="isCommodityLinked" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="isConvertibleOrExchangeable" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="100"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="isCorridor" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="priceAtIssue" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="issueSize" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="issueCountry" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="3"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="couponExchangeRate" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="isCovered" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="creditEnhancementFlag" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="isCurrencyLinked" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="currentCoupon" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="currAmtOutstanding" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="datedDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="dayCountConvention" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="100"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="denominationIncrease" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="denominationType" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="200"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="depositoryType" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="100"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="isDualCcy" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="isEmerging" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="hasEquityClawback" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="isEquityLinked" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="exDividendCalc" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="200"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="exDividendDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="hasExDividend" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="isExchangeListed" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="escrowType" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="100"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="externalNotes" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="4000"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="firstCouponDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="isFloat" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="isFundLinked" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="isFunged" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="isGuarantee" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="isInflationProtected" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="accrualStartDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="interestAlternativeCcyCode" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="3"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="interestIndexLinkedFlag" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="isInterestLinked" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="issueCurrency" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="3"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="issueDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="issueName" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="200"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="issueType" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="200"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="issueYield" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="hasLiquidityOptions" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="lastCouponDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="marketRegion" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="100"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="hasMarketEvent" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="maturityAmount" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="maturityDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="maturityPrice" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="maturityType" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="100"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="maxCoupon" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="maxProgramSize" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="minCoupon" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="minDenomination" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="isMTN" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="origDealAmount" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="isPerpetual" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="putType" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="200"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="putSubType" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="200"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="callType" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="200"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="callSubType" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="200"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="optionStyle" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="200"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="optionStyleSubType" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="200"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="assetExchange" type="{}AssetExchange" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="CallSchedule" type="{}CallSchedule" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="PutSchedule" type="{}PutSchedule" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Ratings" type="{}Ratings" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Redemption" type="{}Redemption" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Instrument", propOrder = {
    "instrumentId",
    "datasetId",
    "version",
    "newIssue",
    "instrumentGrade",
    "lastModifiedDate",
    "source",
    "hasAdditionalCredit",
    "alternativePrincipalCcyCode",
    "amtIssuedPublic",
    "auctionType",
    "averageLifeDate",
    "isBankQualified",
    "isBondLinked",
    "benchmarkISIN",
    "instrumentInsuranceType",
    "tranche",
    "instrumentSwapType",
    "businessDayConvention",
    "calculationType",
    "capitalPurpose",
    "classification",
    "classificationSubType",
    "isCommodityLinked",
    "isConvertibleOrExchangeable",
    "isCorridor",
    "priceAtIssue",
    "issueSize",
    "issueCountry",
    "couponExchangeRate",
    "isCovered",
    "creditEnhancementFlag",
    "isCurrencyLinked",
    "currentCoupon",
    "currAmtOutstanding",
    "datedDate",
    "dayCountConvention",
    "denominationIncrease",
    "denominationType",
    "depositoryType",
    "isDualCcy",
    "isEmerging",
    "hasEquityClawback",
    "isEquityLinked",
    "exDividendCalc",
    "exDividendDate",
    "hasExDividend",
    "isExchangeListed",
    "escrowType",
    "externalNotes",
    "firstCouponDate",
    "isFloat",
    "isFundLinked",
    "isFunged",
    "isGuarantee",
    "isInflationProtected",
    "accrualStartDate",
    "interestAlternativeCcyCode",
    "interestIndexLinkedFlag",
    "isInterestLinked",
    "issueCurrency",
    "issueDate",
    "issueName",
    "issueType",
    "issueYield",
    "hasLiquidityOptions",
    "lastCouponDate",
    "marketRegion",
    "hasMarketEvent",
    "maturityAmount",
    "maturityDate",
    "maturityPrice",
    "maturityType",
    "maxCoupon",
    "maxProgramSize",
    "minCoupon",
    "minDenomination",
    "isMTN",
    "origDealAmount",
    "isPerpetual",
    "putType",
    "putSubType",
    "callType",
    "callSubType",
    "optionStyle",
    "optionStyleSubType",
    "assetExchange",
    "callSchedule",
    "putSchedule",
    "ratings",
    "redemption"
})
public class Instrument {

    protected long instrumentId;
    protected long datasetId;
    protected long version;
    protected String newIssue;
    @XmlElement(required = true)
    protected String instrumentGrade;
    @XmlElement(required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar lastModifiedDate;
    @XmlElement(required = true)
    protected String source;
    protected Boolean hasAdditionalCredit;
    protected String alternativePrincipalCcyCode;
    protected Double amtIssuedPublic;
    protected String auctionType;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar averageLifeDate;
    protected Boolean isBankQualified;
    protected Boolean isBondLinked;
    protected String benchmarkISIN;
    protected String instrumentInsuranceType;
    protected String tranche;
    protected String instrumentSwapType;
    protected String businessDayConvention;
    protected String calculationType;
    protected String capitalPurpose;
    protected String classification;
    protected String classificationSubType;
    protected Boolean isCommodityLinked;
    protected String isConvertibleOrExchangeable;
    protected Boolean isCorridor;
    protected Double priceAtIssue;
    protected Double issueSize;
    protected String issueCountry;
    protected Double couponExchangeRate;
    protected Boolean isCovered;
    protected Boolean creditEnhancementFlag;
    protected Boolean isCurrencyLinked;
    protected Double currentCoupon;
    protected Double currAmtOutstanding;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar datedDate;
    protected String dayCountConvention;
    protected Double denominationIncrease;
    protected String denominationType;
    protected String depositoryType;
    protected Boolean isDualCcy;
    protected Boolean isEmerging;
    protected Boolean hasEquityClawback;
    protected Boolean isEquityLinked;
    protected String exDividendCalc;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar exDividendDate;
    protected Boolean hasExDividend;
    protected Boolean isExchangeListed;
    protected String escrowType;
    protected String externalNotes;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar firstCouponDate;
    protected Boolean isFloat;
    protected Boolean isFundLinked;
    protected Boolean isFunged;
    protected Boolean isGuarantee;
    protected Boolean isInflationProtected;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar accrualStartDate;
    protected String interestAlternativeCcyCode;
    protected Boolean interestIndexLinkedFlag;
    protected Boolean isInterestLinked;
    protected String issueCurrency;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar issueDate;
    protected String issueName;
    protected String issueType;
    protected BigDecimal issueYield;
    protected Boolean hasLiquidityOptions;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar lastCouponDate;
    protected String marketRegion;
    protected Boolean hasMarketEvent;
    protected Double maturityAmount;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar maturityDate;
    protected BigDecimal maturityPrice;
    protected String maturityType;
    protected Double maxCoupon;
    protected Double maxProgramSize;
    protected Double minCoupon;
    protected Double minDenomination;
    protected Boolean isMTN;
    protected Double origDealAmount;
    protected Boolean isPerpetual;
    protected String putType;
    protected String putSubType;
    protected String callType;
    protected String callSubType;
    protected String optionStyle;
    protected String optionStyleSubType;
    protected List<AssetExchange> assetExchange;
    @XmlElement(name = "CallSchedule")
    protected List<CallSchedule> callSchedule;
    @XmlElement(name = "PutSchedule")
    protected List<PutSchedule> putSchedule;
    @XmlElement(name = "Ratings")
    protected List<Ratings> ratings;
    @XmlElement(name = "Redemption")
    protected List<Redemption> redemption;

    /**
     * Gets the value of the instrumentId property.
     * 
     */
    public long getInstrumentId() {
        return instrumentId;
    }

    /**
     * Sets the value of the instrumentId property.
     * 
     */
    public void setInstrumentId(long value) {
        this.instrumentId = value;
    }

    /**
     * Gets the value of the datasetId property.
     * 
     */
    public long getDatasetId() {
        return datasetId;
    }

    /**
     * Sets the value of the datasetId property.
     * 
     */
    public void setDatasetId(long value) {
        this.datasetId = value;
    }

    /**
     * Gets the value of the version property.
     * 
     */
    public long getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     */
    public void setVersion(long value) {
        this.version = value;
    }

    /**
     * Gets the value of the newIssue property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNewIssue() {
        return newIssue;
    }

    /**
     * Sets the value of the newIssue property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNewIssue(String value) {
        this.newIssue = value;
    }

    /**
     * Gets the value of the instrumentGrade property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInstrumentGrade() {
        return instrumentGrade;
    }

    /**
     * Sets the value of the instrumentGrade property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInstrumentGrade(String value) {
        this.instrumentGrade = value;
    }

    /**
     * Gets the value of the lastModifiedDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getLastModifiedDate() {
        return lastModifiedDate;
    }

    /**
     * Sets the value of the lastModifiedDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setLastModifiedDate(XMLGregorianCalendar value) {
        this.lastModifiedDate = value;
    }

    /**
     * Gets the value of the source property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSource() {
        return source;
    }

    /**
     * Sets the value of the source property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSource(String value) {
        this.source = value;
    }

    /**
     * Gets the value of the hasAdditionalCredit property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isHasAdditionalCredit() {
        return hasAdditionalCredit;
    }

    /**
     * Sets the value of the hasAdditionalCredit property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setHasAdditionalCredit(Boolean value) {
        this.hasAdditionalCredit = value;
    }

    /**
     * Gets the value of the alternativePrincipalCcyCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAlternativePrincipalCcyCode() {
        return alternativePrincipalCcyCode;
    }

    /**
     * Sets the value of the alternativePrincipalCcyCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAlternativePrincipalCcyCode(String value) {
        this.alternativePrincipalCcyCode = value;
    }

    /**
     * Gets the value of the amtIssuedPublic property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getAmtIssuedPublic() {
        return amtIssuedPublic;
    }

    /**
     * Sets the value of the amtIssuedPublic property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setAmtIssuedPublic(Double value) {
        this.amtIssuedPublic = value;
    }

    /**
     * Gets the value of the auctionType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAuctionType() {
        return auctionType;
    }

    /**
     * Sets the value of the auctionType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAuctionType(String value) {
        this.auctionType = value;
    }

    /**
     * Gets the value of the averageLifeDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getAverageLifeDate() {
        return averageLifeDate;
    }

    /**
     * Sets the value of the averageLifeDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setAverageLifeDate(XMLGregorianCalendar value) {
        this.averageLifeDate = value;
    }

    /**
     * Gets the value of the isBankQualified property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsBankQualified() {
        return isBankQualified;
    }

    /**
     * Sets the value of the isBankQualified property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsBankQualified(Boolean value) {
        this.isBankQualified = value;
    }

    /**
     * Gets the value of the isBondLinked property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsBondLinked() {
        return isBondLinked;
    }

    /**
     * Sets the value of the isBondLinked property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsBondLinked(Boolean value) {
        this.isBondLinked = value;
    }

    /**
     * Gets the value of the benchmarkISIN property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBenchmarkISIN() {
        return benchmarkISIN;
    }

    /**
     * Sets the value of the benchmarkISIN property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBenchmarkISIN(String value) {
        this.benchmarkISIN = value;
    }

    /**
     * Gets the value of the instrumentInsuranceType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInstrumentInsuranceType() {
        return instrumentInsuranceType;
    }

    /**
     * Sets the value of the instrumentInsuranceType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInstrumentInsuranceType(String value) {
        this.instrumentInsuranceType = value;
    }

    /**
     * Gets the value of the tranche property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTranche() {
        return tranche;
    }

    /**
     * Sets the value of the tranche property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTranche(String value) {
        this.tranche = value;
    }

    /**
     * Gets the value of the instrumentSwapType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInstrumentSwapType() {
        return instrumentSwapType;
    }

    /**
     * Sets the value of the instrumentSwapType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInstrumentSwapType(String value) {
        this.instrumentSwapType = value;
    }

    /**
     * Gets the value of the businessDayConvention property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBusinessDayConvention() {
        return businessDayConvention;
    }

    /**
     * Sets the value of the businessDayConvention property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBusinessDayConvention(String value) {
        this.businessDayConvention = value;
    }

    /**
     * Gets the value of the calculationType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCalculationType() {
        return calculationType;
    }

    /**
     * Sets the value of the calculationType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCalculationType(String value) {
        this.calculationType = value;
    }

    /**
     * Gets the value of the capitalPurpose property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCapitalPurpose() {
        return capitalPurpose;
    }

    /**
     * Sets the value of the capitalPurpose property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCapitalPurpose(String value) {
        this.capitalPurpose = value;
    }

    /**
     * Gets the value of the classification property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClassification() {
        return classification;
    }

    /**
     * Sets the value of the classification property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClassification(String value) {
        this.classification = value;
    }

    /**
     * Gets the value of the classificationSubType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClassificationSubType() {
        return classificationSubType;
    }

    /**
     * Sets the value of the classificationSubType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClassificationSubType(String value) {
        this.classificationSubType = value;
    }

    /**
     * Gets the value of the isCommodityLinked property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsCommodityLinked() {
        return isCommodityLinked;
    }

    /**
     * Sets the value of the isCommodityLinked property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsCommodityLinked(Boolean value) {
        this.isCommodityLinked = value;
    }

    /**
     * Gets the value of the isConvertibleOrExchangeable property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsConvertibleOrExchangeable() {
        return isConvertibleOrExchangeable;
    }

    /**
     * Sets the value of the isConvertibleOrExchangeable property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsConvertibleOrExchangeable(String value) {
        this.isConvertibleOrExchangeable = value;
    }

    /**
     * Gets the value of the isCorridor property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsCorridor() {
        return isCorridor;
    }

    /**
     * Sets the value of the isCorridor property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsCorridor(Boolean value) {
        this.isCorridor = value;
    }

    /**
     * Gets the value of the priceAtIssue property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getPriceAtIssue() {
        return priceAtIssue;
    }

    /**
     * Sets the value of the priceAtIssue property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setPriceAtIssue(Double value) {
        this.priceAtIssue = value;
    }

    /**
     * Gets the value of the issueSize property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getIssueSize() {
        return issueSize;
    }

    /**
     * Sets the value of the issueSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setIssueSize(Double value) {
        this.issueSize = value;
    }

    /**
     * Gets the value of the issueCountry property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIssueCountry() {
        return issueCountry;
    }

    /**
     * Sets the value of the issueCountry property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIssueCountry(String value) {
        this.issueCountry = value;
    }

    /**
     * Gets the value of the couponExchangeRate property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getCouponExchangeRate() {
        return couponExchangeRate;
    }

    /**
     * Sets the value of the couponExchangeRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setCouponExchangeRate(Double value) {
        this.couponExchangeRate = value;
    }

    /**
     * Gets the value of the isCovered property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsCovered() {
        return isCovered;
    }

    /**
     * Sets the value of the isCovered property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsCovered(Boolean value) {
        this.isCovered = value;
    }

    /**
     * Gets the value of the creditEnhancementFlag property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isCreditEnhancementFlag() {
        return creditEnhancementFlag;
    }

    /**
     * Sets the value of the creditEnhancementFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setCreditEnhancementFlag(Boolean value) {
        this.creditEnhancementFlag = value;
    }

    /**
     * Gets the value of the isCurrencyLinked property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsCurrencyLinked() {
        return isCurrencyLinked;
    }

    /**
     * Sets the value of the isCurrencyLinked property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsCurrencyLinked(Boolean value) {
        this.isCurrencyLinked = value;
    }

    /**
     * Gets the value of the currentCoupon property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getCurrentCoupon() {
        return currentCoupon;
    }

    /**
     * Sets the value of the currentCoupon property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setCurrentCoupon(Double value) {
        this.currentCoupon = value;
    }

    /**
     * Gets the value of the currAmtOutstanding property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getCurrAmtOutstanding() {
        return currAmtOutstanding;
    }

    /**
     * Sets the value of the currAmtOutstanding property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setCurrAmtOutstanding(Double value) {
        this.currAmtOutstanding = value;
    }

    /**
     * Gets the value of the datedDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDatedDate() {
        return datedDate;
    }

    /**
     * Sets the value of the datedDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDatedDate(XMLGregorianCalendar value) {
        this.datedDate = value;
    }

    /**
     * Gets the value of the dayCountConvention property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDayCountConvention() {
        return dayCountConvention;
    }

    /**
     * Sets the value of the dayCountConvention property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDayCountConvention(String value) {
        this.dayCountConvention = value;
    }

    /**
     * Gets the value of the denominationIncrease property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getDenominationIncrease() {
        return denominationIncrease;
    }

    /**
     * Sets the value of the denominationIncrease property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setDenominationIncrease(Double value) {
        this.denominationIncrease = value;
    }

    /**
     * Gets the value of the denominationType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDenominationType() {
        return denominationType;
    }

    /**
     * Sets the value of the denominationType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDenominationType(String value) {
        this.denominationType = value;
    }

    /**
     * Gets the value of the depositoryType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDepositoryType() {
        return depositoryType;
    }

    /**
     * Sets the value of the depositoryType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDepositoryType(String value) {
        this.depositoryType = value;
    }

    /**
     * Gets the value of the isDualCcy property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsDualCcy() {
        return isDualCcy;
    }

    /**
     * Sets the value of the isDualCcy property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsDualCcy(Boolean value) {
        this.isDualCcy = value;
    }

    /**
     * Gets the value of the isEmerging property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsEmerging() {
        return isEmerging;
    }

    /**
     * Sets the value of the isEmerging property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsEmerging(Boolean value) {
        this.isEmerging = value;
    }

    /**
     * Gets the value of the hasEquityClawback property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isHasEquityClawback() {
        return hasEquityClawback;
    }

    /**
     * Sets the value of the hasEquityClawback property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setHasEquityClawback(Boolean value) {
        this.hasEquityClawback = value;
    }

    /**
     * Gets the value of the isEquityLinked property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsEquityLinked() {
        return isEquityLinked;
    }

    /**
     * Sets the value of the isEquityLinked property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsEquityLinked(Boolean value) {
        this.isEquityLinked = value;
    }

    /**
     * Gets the value of the exDividendCalc property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExDividendCalc() {
        return exDividendCalc;
    }

    /**
     * Sets the value of the exDividendCalc property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExDividendCalc(String value) {
        this.exDividendCalc = value;
    }

    /**
     * Gets the value of the exDividendDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getExDividendDate() {
        return exDividendDate;
    }

    /**
     * Sets the value of the exDividendDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setExDividendDate(XMLGregorianCalendar value) {
        this.exDividendDate = value;
    }

    /**
     * Gets the value of the hasExDividend property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isHasExDividend() {
        return hasExDividend;
    }

    /**
     * Sets the value of the hasExDividend property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setHasExDividend(Boolean value) {
        this.hasExDividend = value;
    }

    /**
     * Gets the value of the isExchangeListed property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsExchangeListed() {
        return isExchangeListed;
    }

    /**
     * Sets the value of the isExchangeListed property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsExchangeListed(Boolean value) {
        this.isExchangeListed = value;
    }

    /**
     * Gets the value of the escrowType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEscrowType() {
        return escrowType;
    }

    /**
     * Sets the value of the escrowType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEscrowType(String value) {
        this.escrowType = value;
    }

    /**
     * Gets the value of the externalNotes property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExternalNotes() {
        return externalNotes;
    }

    /**
     * Sets the value of the externalNotes property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExternalNotes(String value) {
        this.externalNotes = value;
    }

    /**
     * Gets the value of the firstCouponDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFirstCouponDate() {
        return firstCouponDate;
    }

    /**
     * Sets the value of the firstCouponDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFirstCouponDate(XMLGregorianCalendar value) {
        this.firstCouponDate = value;
    }

    /**
     * Gets the value of the isFloat property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsFloat() {
        return isFloat;
    }

    /**
     * Sets the value of the isFloat property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsFloat(Boolean value) {
        this.isFloat = value;
    }

    /**
     * Gets the value of the isFundLinked property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsFundLinked() {
        return isFundLinked;
    }

    /**
     * Sets the value of the isFundLinked property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsFundLinked(Boolean value) {
        this.isFundLinked = value;
    }

    /**
     * Gets the value of the isFunged property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsFunged() {
        return isFunged;
    }

    /**
     * Sets the value of the isFunged property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsFunged(Boolean value) {
        this.isFunged = value;
    }

    /**
     * Gets the value of the isGuarantee property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsGuarantee() {
        return isGuarantee;
    }

    /**
     * Sets the value of the isGuarantee property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsGuarantee(Boolean value) {
        this.isGuarantee = value;
    }

    /**
     * Gets the value of the isInflationProtected property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsInflationProtected() {
        return isInflationProtected;
    }

    /**
     * Sets the value of the isInflationProtected property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsInflationProtected(Boolean value) {
        this.isInflationProtected = value;
    }

    /**
     * Gets the value of the accrualStartDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getAccrualStartDate() {
        return accrualStartDate;
    }

    /**
     * Sets the value of the accrualStartDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setAccrualStartDate(XMLGregorianCalendar value) {
        this.accrualStartDate = value;
    }

    /**
     * Gets the value of the interestAlternativeCcyCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInterestAlternativeCcyCode() {
        return interestAlternativeCcyCode;
    }

    /**
     * Sets the value of the interestAlternativeCcyCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInterestAlternativeCcyCode(String value) {
        this.interestAlternativeCcyCode = value;
    }

    /**
     * Gets the value of the interestIndexLinkedFlag property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isInterestIndexLinkedFlag() {
        return interestIndexLinkedFlag;
    }

    /**
     * Sets the value of the interestIndexLinkedFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setInterestIndexLinkedFlag(Boolean value) {
        this.interestIndexLinkedFlag = value;
    }

    /**
     * Gets the value of the isInterestLinked property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsInterestLinked() {
        return isInterestLinked;
    }

    /**
     * Sets the value of the isInterestLinked property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsInterestLinked(Boolean value) {
        this.isInterestLinked = value;
    }

    /**
     * Gets the value of the issueCurrency property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIssueCurrency() {
        return issueCurrency;
    }

    /**
     * Sets the value of the issueCurrency property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIssueCurrency(String value) {
        this.issueCurrency = value;
    }

    /**
     * Gets the value of the issueDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getIssueDate() {
        return issueDate;
    }

    /**
     * Sets the value of the issueDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setIssueDate(XMLGregorianCalendar value) {
        this.issueDate = value;
    }

    /**
     * Gets the value of the issueName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIssueName() {
        return issueName;
    }

    /**
     * Sets the value of the issueName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIssueName(String value) {
        this.issueName = value;
    }

    /**
     * Gets the value of the issueType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIssueType() {
        return issueType;
    }

    /**
     * Sets the value of the issueType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIssueType(String value) {
        this.issueType = value;
    }

    /**
     * Gets the value of the issueYield property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getIssueYield() {
        return issueYield;
    }

    /**
     * Sets the value of the issueYield property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setIssueYield(BigDecimal value) {
        this.issueYield = value;
    }

    /**
     * Gets the value of the hasLiquidityOptions property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isHasLiquidityOptions() {
        return hasLiquidityOptions;
    }

    /**
     * Sets the value of the hasLiquidityOptions property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setHasLiquidityOptions(Boolean value) {
        this.hasLiquidityOptions = value;
    }

    /**
     * Gets the value of the lastCouponDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getLastCouponDate() {
        return lastCouponDate;
    }

    /**
     * Sets the value of the lastCouponDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setLastCouponDate(XMLGregorianCalendar value) {
        this.lastCouponDate = value;
    }

    /**
     * Gets the value of the marketRegion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMarketRegion() {
        return marketRegion;
    }

    /**
     * Sets the value of the marketRegion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMarketRegion(String value) {
        this.marketRegion = value;
    }

    /**
     * Gets the value of the hasMarketEvent property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isHasMarketEvent() {
        return hasMarketEvent;
    }

    /**
     * Sets the value of the hasMarketEvent property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setHasMarketEvent(Boolean value) {
        this.hasMarketEvent = value;
    }

    /**
     * Gets the value of the maturityAmount property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getMaturityAmount() {
        return maturityAmount;
    }

    /**
     * Sets the value of the maturityAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setMaturityAmount(Double value) {
        this.maturityAmount = value;
    }

    /**
     * Gets the value of the maturityDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getMaturityDate() {
        return maturityDate;
    }

    /**
     * Sets the value of the maturityDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setMaturityDate(XMLGregorianCalendar value) {
        this.maturityDate = value;
    }

    /**
     * Gets the value of the maturityPrice property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getMaturityPrice() {
        return maturityPrice;
    }

    /**
     * Sets the value of the maturityPrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setMaturityPrice(BigDecimal value) {
        this.maturityPrice = value;
    }

    /**
     * Gets the value of the maturityType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMaturityType() {
        return maturityType;
    }

    /**
     * Sets the value of the maturityType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMaturityType(String value) {
        this.maturityType = value;
    }

    /**
     * Gets the value of the maxCoupon property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getMaxCoupon() {
        return maxCoupon;
    }

    /**
     * Sets the value of the maxCoupon property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setMaxCoupon(Double value) {
        this.maxCoupon = value;
    }

    /**
     * Gets the value of the maxProgramSize property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getMaxProgramSize() {
        return maxProgramSize;
    }

    /**
     * Sets the value of the maxProgramSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setMaxProgramSize(Double value) {
        this.maxProgramSize = value;
    }

    /**
     * Gets the value of the minCoupon property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getMinCoupon() {
        return minCoupon;
    }

    /**
     * Sets the value of the minCoupon property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setMinCoupon(Double value) {
        this.minCoupon = value;
    }

    /**
     * Gets the value of the minDenomination property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getMinDenomination() {
        return minDenomination;
    }

    /**
     * Sets the value of the minDenomination property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setMinDenomination(Double value) {
        this.minDenomination = value;
    }

    /**
     * Gets the value of the isMTN property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsMTN() {
        return isMTN;
    }

    /**
     * Sets the value of the isMTN property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsMTN(Boolean value) {
        this.isMTN = value;
    }

    /**
     * Gets the value of the origDealAmount property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getOrigDealAmount() {
        return origDealAmount;
    }

    /**
     * Sets the value of the origDealAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setOrigDealAmount(Double value) {
        this.origDealAmount = value;
    }

    /**
     * Gets the value of the isPerpetual property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsPerpetual() {
        return isPerpetual;
    }

    /**
     * Sets the value of the isPerpetual property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsPerpetual(Boolean value) {
        this.isPerpetual = value;
    }

    /**
     * Gets the value of the putType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPutType() {
        return putType;
    }

    /**
     * Sets the value of the putType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPutType(String value) {
        this.putType = value;
    }

    /**
     * Gets the value of the putSubType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPutSubType() {
        return putSubType;
    }

    /**
     * Sets the value of the putSubType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPutSubType(String value) {
        this.putSubType = value;
    }

    /**
     * Gets the value of the callType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCallType() {
        return callType;
    }

    /**
     * Sets the value of the callType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCallType(String value) {
        this.callType = value;
    }

    /**
     * Gets the value of the callSubType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCallSubType() {
        return callSubType;
    }

    /**
     * Sets the value of the callSubType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCallSubType(String value) {
        this.callSubType = value;
    }

    /**
     * Gets the value of the optionStyle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOptionStyle() {
        return optionStyle;
    }

    /**
     * Sets the value of the optionStyle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOptionStyle(String value) {
        this.optionStyle = value;
    }

    /**
     * Gets the value of the optionStyleSubType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOptionStyleSubType() {
        return optionStyleSubType;
    }

    /**
     * Sets the value of the optionStyleSubType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOptionStyleSubType(String value) {
        this.optionStyleSubType = value;
    }

    /**
     * Gets the value of the assetExchange property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the assetExchange property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAssetExchange().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AssetExchange }
     * 
     * 
     */
    public List<AssetExchange> getAssetExchange() {
        if (assetExchange == null) {
            assetExchange = new ArrayList<AssetExchange>();
        }
        return this.assetExchange;
    }

    /**
     * Gets the value of the callSchedule property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the callSchedule property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCallSchedule().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CallSchedule }
     * 
     * 
     */
    public List<CallSchedule> getCallSchedule() {
        if (callSchedule == null) {
            callSchedule = new ArrayList<CallSchedule>();
        }
        return this.callSchedule;
    }

    /**
     * Gets the value of the putSchedule property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the putSchedule property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPutSchedule().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PutSchedule }
     * 
     * 
     */
    public List<PutSchedule> getPutSchedule() {
        if (putSchedule == null) {
            putSchedule = new ArrayList<PutSchedule>();
        }
        return this.putSchedule;
    }

    /**
     * Gets the value of the ratings property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the ratings property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRatings().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Ratings }
     * 
     * 
     */
    public List<Ratings> getRatings() {
        if (ratings == null) {
            ratings = new ArrayList<Ratings>();
        }
        return this.ratings;
    }

    /**
     * Gets the value of the redemption property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the redemption property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRedemption().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Redemption }
     * 
     * 
     */
    public List<Redemption> getRedemption() {
        if (redemption == null) {
            redemption = new ArrayList<Redemption>();
        }
        return this.redemption;
    }

}
