//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.06 at 03:53:18 PM IST 
//


package com.concept.crew.info.jaxb;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.concept.crew.info.jaxb package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _StartingTag_QNAME = new QName("", "StartingTag");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.concept.crew.info.jaxb
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Redemption }
     * 
     */
    public Redemption createRedemption() {
        return new Redemption();
    }

    /**
     * Create an instance of {@link CallSchedule }
     * 
     */
    public CallSchedule createCallSchedule() {
        return new CallSchedule();
    }

    /**
     * Create an instance of {@link Instrument }
     * 
     */
    public Instrument createInstrument() {
        return new Instrument();
    }

    /**
     * Create an instance of {@link PutSchedule }
     * 
     */
    public PutSchedule createPutSchedule() {
        return new PutSchedule();
    }

    /**
     * Create an instance of {@link Ratings }
     * 
     */
    public Ratings createRatings() {
        return new Ratings();
    }

    /**
     * Create an instance of {@link AssetExchange }
     * 
     */
    public AssetExchange createAssetExchange() {
        return new AssetExchange();
    }

    /**
     * Create an instance of {@link StartingTag }
     * 
     */
    public StartingTag createStartingTag() {
        return new StartingTag();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link StartingTag }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "StartingTag")
    public JAXBElement<StartingTag> createStartingTag(StartingTag value) {
        return new JAXBElement<StartingTag>(_StartingTag_QNAME, StartingTag.class, null, value);
    }

}
