//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.15 at 11:31:31 PM IST 
//


package com.concept.crew.info.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for Ratings complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Ratings">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ratingType" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="100"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ratingProvider" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="100"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ratingEffectiveDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="rating" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="100"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ratingsSource" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="30"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ratingOutlook" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="50"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ratingWatch" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="50"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ratingEndDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="isIssuerOrInstrumentRating" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="20"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Ratings", propOrder = {
    "ratingType",
    "ratingProvider",
    "ratingEffectiveDate",
    "rating",
    "ratingsSource",
    "ratingOutlook",
    "ratingWatch",
    "ratingEndDate",
    "isIssuerOrInstrumentRating"
})
public class Ratings {

    protected String ratingType;
    protected String ratingProvider;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar ratingEffectiveDate;
    protected String rating;
    protected String ratingsSource;
    protected String ratingOutlook;
    protected String ratingWatch;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar ratingEndDate;
    protected String isIssuerOrInstrumentRating;

    /**
     * Gets the value of the ratingType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRatingType() {
        return ratingType;
    }

    /**
     * Sets the value of the ratingType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRatingType(String value) {
        this.ratingType = value;
    }

    /**
     * Gets the value of the ratingProvider property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRatingProvider() {
        return ratingProvider;
    }

    /**
     * Sets the value of the ratingProvider property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRatingProvider(String value) {
        this.ratingProvider = value;
    }

    /**
     * Gets the value of the ratingEffectiveDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getRatingEffectiveDate() {
        return ratingEffectiveDate;
    }

    /**
     * Sets the value of the ratingEffectiveDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setRatingEffectiveDate(XMLGregorianCalendar value) {
        this.ratingEffectiveDate = value;
    }

    /**
     * Gets the value of the rating property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRating() {
        return rating;
    }

    /**
     * Sets the value of the rating property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRating(String value) {
        this.rating = value;
    }

    /**
     * Gets the value of the ratingsSource property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRatingsSource() {
        return ratingsSource;
    }

    /**
     * Sets the value of the ratingsSource property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRatingsSource(String value) {
        this.ratingsSource = value;
    }

    /**
     * Gets the value of the ratingOutlook property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRatingOutlook() {
        return ratingOutlook;
    }

    /**
     * Sets the value of the ratingOutlook property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRatingOutlook(String value) {
        this.ratingOutlook = value;
    }

    /**
     * Gets the value of the ratingWatch property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRatingWatch() {
        return ratingWatch;
    }

    /**
     * Sets the value of the ratingWatch property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRatingWatch(String value) {
        this.ratingWatch = value;
    }

    /**
     * Gets the value of the ratingEndDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getRatingEndDate() {
        return ratingEndDate;
    }

    /**
     * Sets the value of the ratingEndDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setRatingEndDate(XMLGregorianCalendar value) {
        this.ratingEndDate = value;
    }

    /**
     * Gets the value of the isIssuerOrInstrumentRating property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsIssuerOrInstrumentRating() {
        return isIssuerOrInstrumentRating;
    }

    /**
     * Sets the value of the isIssuerOrInstrumentRating property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsIssuerOrInstrumentRating(String value) {
        this.isIssuerOrInstrumentRating = value;
    }

}
