//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.05.06 at 03:53:18 PM IST 
//


package com.concept.crew.info.jaxb;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for Redemption complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Redemption">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="redemptionSource" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="30"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="amount" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="date" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="redemptionMethod" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="100"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="redemptionStrikePrice" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="redemptionType" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="100"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="redemptionValue" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="redenominatedExchangeRate" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="refundingDatedDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="refundingSettleDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="currAmtOutstandingEffectiveDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="amtChangeType" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="100"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="redemptionCashFlow" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="reofferReopenPrice" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="reofferReopenSpread" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="reofferReopenYield" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="caAnnouncementDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="amountOutstanding" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Redemption", propOrder = {
    "redemptionSource",
    "amount",
    "date",
    "redemptionMethod",
    "redemptionStrikePrice",
    "redemptionType",
    "redemptionValue",
    "redenominatedExchangeRate",
    "refundingDatedDate",
    "refundingSettleDate",
    "currAmtOutstandingEffectiveDate",
    "amtChangeType",
    "redemptionCashFlow",
    "reofferReopenPrice",
    "reofferReopenSpread",
    "reofferReopenYield",
    "caAnnouncementDate",
    "amountOutstanding"
})
public class Redemption {

    protected String redemptionSource;
    protected Double amount;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar date;
    protected String redemptionMethod;
    protected BigDecimal redemptionStrikePrice;
    protected String redemptionType;
    protected Double redemptionValue;
    protected Double redenominatedExchangeRate;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar refundingDatedDate;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar refundingSettleDate;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar currAmtOutstandingEffectiveDate;
    protected String amtChangeType;
    protected Double redemptionCashFlow;
    protected Double reofferReopenPrice;
    protected BigDecimal reofferReopenSpread;
    protected BigDecimal reofferReopenYield;
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar caAnnouncementDate;
    protected Double amountOutstanding;

    /**
     * Gets the value of the redemptionSource property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRedemptionSource() {
        return redemptionSource;
    }

    /**
     * Sets the value of the redemptionSource property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRedemptionSource(String value) {
        this.redemptionSource = value;
    }

    /**
     * Gets the value of the amount property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getAmount() {
        return amount;
    }

    /**
     * Sets the value of the amount property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setAmount(Double value) {
        this.amount = value;
    }

    /**
     * Gets the value of the date property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDate() {
        return date;
    }

    /**
     * Sets the value of the date property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDate(XMLGregorianCalendar value) {
        this.date = value;
    }

    /**
     * Gets the value of the redemptionMethod property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRedemptionMethod() {
        return redemptionMethod;
    }

    /**
     * Sets the value of the redemptionMethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRedemptionMethod(String value) {
        this.redemptionMethod = value;
    }

    /**
     * Gets the value of the redemptionStrikePrice property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getRedemptionStrikePrice() {
        return redemptionStrikePrice;
    }

    /**
     * Sets the value of the redemptionStrikePrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setRedemptionStrikePrice(BigDecimal value) {
        this.redemptionStrikePrice = value;
    }

    /**
     * Gets the value of the redemptionType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRedemptionType() {
        return redemptionType;
    }

    /**
     * Sets the value of the redemptionType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRedemptionType(String value) {
        this.redemptionType = value;
    }

    /**
     * Gets the value of the redemptionValue property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getRedemptionValue() {
        return redemptionValue;
    }

    /**
     * Sets the value of the redemptionValue property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setRedemptionValue(Double value) {
        this.redemptionValue = value;
    }

    /**
     * Gets the value of the redenominatedExchangeRate property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getRedenominatedExchangeRate() {
        return redenominatedExchangeRate;
    }

    /**
     * Sets the value of the redenominatedExchangeRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setRedenominatedExchangeRate(Double value) {
        this.redenominatedExchangeRate = value;
    }

    /**
     * Gets the value of the refundingDatedDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getRefundingDatedDate() {
        return refundingDatedDate;
    }

    /**
     * Sets the value of the refundingDatedDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setRefundingDatedDate(XMLGregorianCalendar value) {
        this.refundingDatedDate = value;
    }

    /**
     * Gets the value of the refundingSettleDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getRefundingSettleDate() {
        return refundingSettleDate;
    }

    /**
     * Sets the value of the refundingSettleDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setRefundingSettleDate(XMLGregorianCalendar value) {
        this.refundingSettleDate = value;
    }

    /**
     * Gets the value of the currAmtOutstandingEffectiveDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCurrAmtOutstandingEffectiveDate() {
        return currAmtOutstandingEffectiveDate;
    }

    /**
     * Sets the value of the currAmtOutstandingEffectiveDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCurrAmtOutstandingEffectiveDate(XMLGregorianCalendar value) {
        this.currAmtOutstandingEffectiveDate = value;
    }

    /**
     * Gets the value of the amtChangeType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAmtChangeType() {
        return amtChangeType;
    }

    /**
     * Sets the value of the amtChangeType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAmtChangeType(String value) {
        this.amtChangeType = value;
    }

    /**
     * Gets the value of the redemptionCashFlow property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getRedemptionCashFlow() {
        return redemptionCashFlow;
    }

    /**
     * Sets the value of the redemptionCashFlow property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setRedemptionCashFlow(Double value) {
        this.redemptionCashFlow = value;
    }

    /**
     * Gets the value of the reofferReopenPrice property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getReofferReopenPrice() {
        return reofferReopenPrice;
    }

    /**
     * Sets the value of the reofferReopenPrice property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setReofferReopenPrice(Double value) {
        this.reofferReopenPrice = value;
    }

    /**
     * Gets the value of the reofferReopenSpread property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getReofferReopenSpread() {
        return reofferReopenSpread;
    }

    /**
     * Sets the value of the reofferReopenSpread property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setReofferReopenSpread(BigDecimal value) {
        this.reofferReopenSpread = value;
    }

    /**
     * Gets the value of the reofferReopenYield property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getReofferReopenYield() {
        return reofferReopenYield;
    }

    /**
     * Sets the value of the reofferReopenYield property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setReofferReopenYield(BigDecimal value) {
        this.reofferReopenYield = value;
    }

    /**
     * Gets the value of the caAnnouncementDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getCaAnnouncementDate() {
        return caAnnouncementDate;
    }

    /**
     * Sets the value of the caAnnouncementDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setCaAnnouncementDate(XMLGregorianCalendar value) {
        this.caAnnouncementDate = value;
    }

    /**
     * Gets the value of the amountOutstanding property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getAmountOutstanding() {
        return amountOutstanding;
    }

    /**
     * Sets the value of the amountOutstanding property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setAmountOutstanding(Double value) {
        this.amountOutstanding = value;
    }

}
